### ISSUE TITLE
Access module not updating 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Accessibility#1]
Upon interaction with grid, access layer is not updating. Module is down?

**Comment by doorleyr** [comment]
It's running again now. It hadn't been running because an error was thrown. The module expects all grid cell values to be in the form of a list eg. [1,1] but after running for some time it got a grid cell value that was not in this form. Is there some situation when the scanner module sends some other value for a grid cell (eg. a None Type or something)?

**Comment by RELNO** [comment]
Non types are in the form of [-1,-1]. What was the error?
